# Generated by Django 5.0.6 on 2024-10-08 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0002_blog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-created_at']},
        ),
    ]
