# Generated by Django 5.0.6 on 2024-10-08 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0003_alter_blog_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-updated_at']},
        ),
    ]
