# Generated by Django 5.0.6 on 2024-10-08 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0004_alter_blog_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='status',
            name='image',
            field=models.ImageField(default='img/default.jpg', upload_to='img/'),
        ),
    ]
