# Generated by Django 5.0.6 on 2024-10-08 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminapp', '0005_status_image'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='status',
            table='Status',
        ),
    ]
